name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Yarn Install
        run: yarn install
      - name: Push translations
        uses: transifex/cli-action@v1
        with:
          token: ${{ secrets.TX_TOKEN }}
          args: push
      - run: rm -rf /tmp/tx
      - name: Pull translations
        uses: transifex/cli-action@v1
        with:
          token: ${{ secrets.TX_TOKEN }}
          args: pull
      - name: Build
        run: yarn build
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with: 
          ref: master
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Clean ftp
        uses: StephanThierry/ftp-delete-action@v2.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          workingDir: /www
          remoteFiles: "precache-manifest.*.js;.ftp-deploy-sync-state.json"
          remoteDirectories: "js;css"
      - name: Deploy on ftp
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: www/
          exclude: CNAME
      - name: Deploy on github-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          exclude_assets: "proxy.php"
