name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - name: pnpm install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run unit tests
        run: pnpm test:unit
